
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [4]:
import numpy as np

array = np.arange(10)

print(array)


[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
import numpy as np

array = np.arange(9)

matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [3]:
import numpy as np

array = np.arange(9)

matrix = array.reshape(3, 3)

element = matrix[1, 1]

print(element)


4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [12]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

addition = array1 + array2
print("Addition:", addition)

subtraction = array1 - array2
print("Subtraction:", subtraction)

multiplication = array1 * array2
print("Multiplication:", multiplication)

division = array1 / array2
print("Division:", division)



Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [9]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

sum_array = np.sum(array)
mean_array = np.mean(array)
std_dev_array = np.std(array)

print("Sum:", sum_array)
print("Mean:", mean_array)
print("Standard Deviation:", std_dev_array)


Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [10]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = array.reshape(2, 3)

print(reshaped_array)


[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [11]:
import numpy as np

random_array = np.random.randint(0, 100, size=(5, 5))

print(random_array)


[[39 38 52  2 63]
 [ 8 80 21 31 13]
 [10 80 18 10 81]
 [ 6 56 35 57 75]
 [85 98 77 74 93]]


Replace all values in the sub-array with a specific value.


In [19]:
random_array_value = random_array [:1,2:] = 10
random_array

array([[39, 38, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [ 6, 56, 10, 10, 10],
       [85, 98, 10, 10, 10]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [34]:
array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
array
array[[1, 3]]


array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [35]:
array = np.array([0,1,2])
array

new_array = np.tile(array, (3,2))
new_array 

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [37]:
import numpy as np

array_2d = np.array([[0, 1, 2],
                     [0, 1, 2],
                     [0, 1, 2]])

add_array = np.array([10, 20, 30])

result_array = array_2d + add_array

result_array


array([[10, 21, 32],
       [10, 21, 32],
       [10, 21, 32]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [41]:
array1 = np.random.randint(0, 100, size=(3, 3))
array2 = np.random.randint(0, 100, size=(3, 3))

concatenated_horizontal = np.hstack((array1, array2))
concatenated_horizontal


array([[81, 83, 71, 28, 18, 34],
       [ 9, 83,  1, 69, 62, 54],
       [50, 60, 61, 64, 35, 99]])

In [40]:
concatenated_vertical = np.vstack((array1, array2))
concatenated_vertical 

array([[75, 94, 40],
       [54, 96, 27],
       [81, 40, 32],
       [91, 98, 59],
       [55,  0,  5],
       [27, 69, 13]])

In [57]:
splitted_array = np.hsplit(concatenated_horizontal, 3)
splitted_array


[array([[81, 83],
        [ 9, 83],
        [50, 60]]),
 array([[71, 28],
        [ 1, 69],
        [61, 64]]),
 array([[18, 34],
        [62, 54],
        [35, 99]])]

In [54]:
splitted_array = np.vsplit(concatenated_vertical, 3)
splitted_array

[array([[75, 94, 40],
        [54, 96, 27]]),
 array([[81, 40, 32],
        [91, 98, 59]]),
 array([[55,  0,  5],
        [27, 69, 13]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [36]:
array = [1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5]

mode = None
max_count = 0

for num in array:
    count = array.count(num)
    if count > max_count:
        mode = num
        max_count = count

print("Mode of the array:", mode)


Mode of the array: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

